blog/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = [
    url(r'^$', views.indexView, name='index'),
    url(r'^(?P<slug>[-_\w]+)/$', views.articleView, name='article'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'portfolio.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
	title = models.CharField(max_length=255, null=True)
	slug = models.CharField(max_length=255, null=True)
	author = models.CharField(max_length=100, null=True)
	image = models.FileField(null=True)
	published = models.DateField(auto_now_add=True)
	content = models.TextField()

	def __unicode__(self):
		return self.title

blog/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from blog.models import Article

# Create your views here.
def indexView(request):
	context = {}
	articles = Article.objects.all().order_by('published')

	context['articles'] = articles
	return render(request, 'blog.html', context)

def articleView(request, slug):
	context = {}

	try:
		article = Article.objects.get(slug=slug)
		context['article'] = article
	except Article.DoesNotExist:
		return redirect(reverse('blog:index'))

	return render(request, 'post.html', context)

blog/templates/blog.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
	{% endblock %}

	{% block title %}Blog | Austin Bailey{% endblock %}

	{% block content %}
		<div class="row" id="blog">
			<div class="overlay">
				<div class="col-3-4 col-centered">
					<h1 class="text-white text-center">Hot off the <span class="red">press</span></h1>
				</div>
			</div>
		</div>
		{% if articles %}
			{% for article in articles %}
				<div class="row m-t-5 m-b-5">
					<div class="col-2-3 col-centered">
						<a class="blog-img" href="{% url 'blog:article' article.title|slugify %}" style="background: url({{ article.image.url }}) center; background-size: cover;">
						</a>
						<a class="blog-title red p-t-2" href="{% url 'blog:article' article.title|slugify %}">{{ article.title }}</a>
						<p class="p-b-2">{{ article.published }} - <span class="red">{{ article.author }}</span></p>
						<p class="p-b-2">{{ article.content|truncatechars:255|removetags:"p"|safe }}</p>
						<a href="{% url 'blog:article' article.title|slugify %}" class="read-more">Read more</a>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<div class="row p-t-5 p-b-5">
				<h1 class="text-center">There are no articles yet. Check back soon!</h1>
			</div>
		{% endif %}
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.min.js' %}"></script>
	{% endblock %}

blog/templates/post.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
	{% endblock %}

	{% block title %}{{ article.title }} | Austin Bailey{% endblock %}
	{% block metaog %}
		<meta property="og:image" content="{{ article.image.url }}" />
		<meta property="og:title" content="{{ article.title }}" />
		<meta property="og:type" content="article" />
    	<meta property="og:description" content="{{ article.content|truncatewords:50 }}" />
    {% endblock %}

	{% block content %}
		<div class="row" id="post-img" style="background: url({{ article.image.url }}) center; background-size: cover;"></div>
		<div class="row p-t-2 p-b-2">
			<div class="col-2-3 col-centered article-content">
				<h1 class="red">{{ article.title }}</h1>
				<h3 class="p-b-5">{{ article.published }} - <span class="red">{{ article.author }}</span></h3>
				{{ article.content|safe }}
			</div>
		</div>
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.min.js' %}"></script>
	{% endblock %}