blog/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = [
    url(r'^$', views.indexView, name='index'),
    url(r'^(?P<slug>[-_\w]+)/$', views.articleView, name='article'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

import views

urlpatterns = [
    url(r'^$', views.indexView, name='index'),
    url(r'^what/$', views.whatView, name='what'),
    url(r'^who/$', views.whoView, name='who'),
    url(r'^contact/$', views.contactView, name='contact'),
    url(r'^lead/$', views.lead_handler, name='lead'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'portfolio.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.core.mail import send_mail
from django.dispatch import receiver
from django.db.models.signals import post_save

class FrontImage(models.Model):
	image = models.FileField()
	active = models.BooleanField()
	text = models.TextField(max_length=140, null=True)

	def __unicode__(self):
		return self.text

class ContactLead(models.Model):
	name = models.CharField(max_length=255)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	company = models.CharField(max_length=50)
	email = models.EmailField(null=True)
	phone = models.CharField(max_length=15)
	need = models.TextField()

	def __unicode__(self):
		return self.name

home/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from home.models import ContactLead

class ContactForm(forms.ModelForm):
	class Meta:
		model = ContactLead
		fields = ['first_name', 'last_name', 'company', 'email', 'phone', 'need']
		labels = {
			'first_name': _('First Name'),
			'last_name': _('Last Name'),
			'company': _('Company'),
			'email': _('Email Address'),
			'phone': _('Phone Number'),
			'need': _('How Can I Help?'),
		}
		widgets = {
			'first_name': forms.TextInput(attrs={'placeholder': 'Austin'}),
			'last_name': forms.TextInput(attrs={'placeholder': 'Bailey'}),
			'company': forms.TextInput(attrs={'placeholder': 'Company XYZ'}),
			'email': forms.EmailInput(attrs={'placeholder': 'austin@austinbailey.rocks'}),
			'phone': forms.TextInput(attrs={'placeholder': '(704) 351-1478'}),
			'need': forms.Textarea(attrs={'placeholder': 'Website redesign, online marketing, social media, etc.'}),
		}

class CTAForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Austin Bailey'}))
	email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'austin@austinbailey.rocks'}))
	phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '(704) 351-1478'}))

home/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
import json

from home.forms import ContactForm, CTAForm
from page_widgets.models import ServiceWidget, HomeDescription, CTAPopUp, HowWidget
from home.models import ContactLead
from blog.models import Article
from home.utils import send_email

# Create your views here.
def indexView(request):
	context = {}
	form = ContactForm()

	try:
		services = ServiceWidget.objects.filter(active=True)[:3]
	except ServiceWidget.DoesNotExist:
		services = False

	try:
		home_desc = HomeDescription.objects.get(active=True)
	except HomeDescription.DoesNotExist:
		home_desc = False
		
	try:
		cta = CTAPopUp.objects.get(active=True)
	except CTAPopUp.DoesNotExist:
		cta = False

	cta_form = CTAForm()

	if request.session.get('lead'):
		context['lead'] = True

	context['form'] = form
	context['cta'] = cta
	context['cta_form'] = cta_form
	context['services'] = services
	context['home_desc'] = home_desc
	return render(request, 'index.html', context)

def whatView(request):
	context = {}
	form = ContactForm()

	try:
		services = ServiceWidget.objects.filter(active=True)[:3]
	except ServiceWidget.DoesNotExist:
		services = False

	try:
		how = HowWidget.objects.get(active=True)
	except HowWidget.DoesNotExist:
		how = False

	context['form'] = form
	context['how'] = how
	context['services'] = services
	return render(request, 'what.html', context)

def whoView(request):
	context = {}
	form = ContactForm()
	cta_form = CTAForm()

	try:
		cta = CTAPopUp.objects.get(active=True)
	except CTAPopUp.DoesNotExist:
		cta = False

	if request.session.get('lead'):
		context['lead'] = True

	context['cta'] = cta
	context['form'] = form
	context['cta_form'] = cta_form
	return render(request, 'who.html', context)

def contactView(request):
	context = {}
	form = ContactForm()

	context['form'] = form
	return render(request, 'contact.html', context)

def lead_handler(request):
	if request.method == 'POST':
		if 'cta_submit' in request.POST:
			request.session['lead'] = True

			name = request.POST.get('name')
			email = request.POST.get('email')
			phone = request.POST.get('phone')

			lead = ContactLead.objects.create(name=name, first_name="cta", last_name="cta", company="cta", email=email, phone=phone, need="cta request")
			lead.save()

			send_email()
			messages.add_message(request, messages.SUCCESS, "Thank you for sending me your information! I'll be in touch with you within the next 24 hours.")
			return redirect(reverse('home:index'))
		if 'contact_submit' in request.POST:
			first_name = request.POST.get('first_name')
			last_name = request.POST.get('last_name')
			company = request.POST.get('company')
			email_addr = request.POST.get('email')
			phone_num = request.POST.get('phone')
			need = request.POST.get('need')
			name = first_name + " " + last_name

			lead = ContactLead.objects.create(name=name, first_name=first_name, last_name=last_name, company=company, email=email_addr, phone=phone_num, need=need)
			lead.save()

			send_email()
			messages.add_message(request, messages.SUCCESS, "Thank you for sending me your information! I'll be in touch with you within the next 24 hours.")
			return redirect(reverse('home:index'))
	else:
		return redirect(reverse('home:index'))

home/templates/base.html
<!DOCTYPE html>
	{% load static from staticfiles %}
<html>
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width">

		{% block stylesheets %}
		{% endblock %}

		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.min.css" />
		<link href='http://fonts.googleapis.com/css?family=Oswald:400,700|Oxygen:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		<link rel="apple-touch-icon" sizes="57x57" href="{% static 'home/i/apple-touch-icon-57x57.png' %}">
		<link rel="apple-touch-icon" sizes="60x60" href="{% static 'home/i/apple-touch-icon-60x60.png' %}">
		<link rel="apple-touch-icon" sizes="72x72" href="{% static 'home/i/apple-touch-icon-72x72.png' %}">
		<link rel="apple-touch-icon" sizes="76x76" href="{% static 'home/i/apple-touch-icon-76x76.png' %}">
		<link rel="apple-touch-icon" sizes="114x114" href="{% static 'home/i/apple-touch-icon-114x114.png' %}">
		<link rel="apple-touch-icon" sizes="120x120" href="{% static 'home/i/apple-touch-icon-120x120.png' %}">
		<link rel="apple-touch-icon" sizes="144x144" href="{% static 'home/i/apple-touch-icon-144x144.png' %}">
		<link rel="apple-touch-icon" sizes="152x152" href="{% static 'home/i/apple-touch-icon-152x152.png' %}">
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'home/i/apple-touch-icon-180x180.png' %}">
		<link rel="icon" type="image/png" href="{% static 'home/i/favicon-32x32.png' %}" sizes="32x32">
		<link rel="icon" type="image/png" href="{% static 'home/i/android-chrome-192x192.png' %}" sizes="192x192">
		<link rel="icon" type="image/png" href="{% static 'home/i/favicon-96x96.png' %}" sizes="96x96">
		<link rel="icon" type="image/png" href="{% static 'home/i/favicon-16x16.png' %}" sizes="16x16">

		<link rel="stylesheet" href="{% static 'home/css/base.min.css' %}" />
		<!--[if lt IE 9]>
		    <script src="{% static 'welcome/js/html5shiv-printshiv.min.js' %}"></script>
		<![endif]-->

		<title>{% block title %}{% endblock %}</title>
		{% block metaog %}
	    	<meta name="description" content="Inbound Marketing Rockstar | Austin Bailey" />
	    {% endblock %}
	</head>
	<body>
		<div class="spinner-container">
			<div class="spinner">
			  <div class="dot1"></div>
			  <div class="dot2"></div>
			</div>
		</div>
		<header>
			<div class="row">
				<div class="container no-pad">
					<div class="col-nav col-centered no-pad">
						<a href="{% url 'home:index' %}" class="navbar-logo">AB</a>
						<a href="#" class="pull-right" id="collapsed">&#x2261;</a>
						<nav class="navbar-collapsable right-menu pull-right">
							<ul class="menu-links">
								<li><a href="{% url 'home:what' %}">What I Do</a></li>
								<li><a href="{% url 'home:who' %}">Who I Am</a></li>
								<li><a href="{% url 'blog:index' %}">Blog</a></li>
								<li><a href="{% url 'home:contact' %}">Contact</a></li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</header>

			{% block content %}
			{% endblock %}
		
		<footer class="red-row p-t-5 p-b-5">
			<div class="container clearfix">
				<div class="col-2-3 col-centered">
					<a href="/" class="footer-logo p-b-2">AB</a>
					<p class="text-white text-center p-b-2">&copy; 2015 Austin Bailey</p>
					<a class="footer-mailto" href="mailto:austin@austinbailey.rocks">austin@austinbailey.rocks</a>
					<nav>
						<ul class="footer-social clearfix">
							<li><a href="https://twitter.com/theaustinbailey"><i class="fa fa-twitter"></i></a></li>
							<li><a href="https://www.facebook.com/austbailey"><i class="fa fa-facebook-f"></i></a></li>
							<li><a href="https://instagram.com/theaustinbailey"><i class="fa fa-instagram"></i></a></li>
							<li><a href="https://plus.google.com/102153233690271136674"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="https://www.linkedin.com/pub/austin-bailey/59/25b/336"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</nav>
				</div>
			</div>
		</footer>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

		{% block javascript %}
		{% endblock %}

	</body>
</html>

home/templates/contact.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
	{% endblock %}

	{% block title %}Work With Me | Austin Bailey{% endblock %}

	{% block content %}
		<div class="row" id="contact">
			<div class="overlay">
				<div class="col-3-4 col-centered">
					<h1 class="text-white text-center">Let me help you take <span class="red">your business</span> to the <span class="red">next level</span></h1>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="container clearfix">
				<div class="col-2-3 p-t-2 p-b-2 col-centered">
					<h2 class="workwme">Work with me</h2>
					<form action="{% url 'home:lead' %}" method="post">
						{% csrf_token %}
						{{ form }}
						<input type="submit" name="contact_submit" class="submit" value="Get In Touch"/>
					</form>
				</div>
			</div>
		</div>
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.min.js' %}"></script>
	{% endblock %}

home/templates/index.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
	{% endblock %}

	{% block title %}Inbound Marketing Rockstar | Austin Bailey{% endblock %}

	{% block content %}
		{% if messages %}
			<div class="thanks-container">
				<div class="container clearfix">
					<div class="col-1-1 col-centered">
						{% for message in messages %}
							<h1 class="text-center text-white">{{ message }}</h1>
						{% endfor %}
						<a href="#close" class="text-white" id="thanks-close">close</a>
					</div>
				</div>
			</div>
		{% endif %}
		{% if not lead %}
			{% if cta %}
				<div class="cta-container" id="{{ cta.title|slugify }}">
					<div class="container clearfix">
						<div class="col-1-1 col-centered">
							<h1 class="text-center text-white">{{ cta.title }}</h1>
							{{ cta.text|safe }}
							<form action="{% url 'home:lead' %}" method="post" id="cta-form">
								{% csrf_token %}
								{% for field in cta_form %}
									{{ field.label_tag }}
									{{ field }}
								{% endfor %}
								<input type="submit" name="cta_submit" class="submit" value="{{ cta.button_text }}"/>
							</form>
							<a href="#close-cta" class="text-white" id="cta-close">close</a>
						</div>
					</div>
				</div>
			{% endif %}
		{% endif %}

		<div class="row" id="big-frnt">
			<div class="overlay">
				<div class="col-3-4 col-centered">
					<h1 class="text-white text-center">Beautiful, data driven websites optimized to convert <span class="red">strangers</span> into <span class="red">customers</span></h1>
				</div>
			</div>
		</div>
		<div class="red-row" id="get-to-know-me">
			<div class="col-3-4 col-centered p-t-5 p-b-5">
				{% if home_desc %}
					<h1 class="text-center text-white">{{ home_desc.title }}</h1>
					<p class="text-center text-white">{{ home_desc.text|safe|removetags:"p" }}</p>
				{% else %}
					<h1 class="text-center text-white">The Difference</h1>
					<p class="text-center text-white">In an information-driven world, people go online now more than ever to conduct their own research before they decide to buy. How is your website working for you if it doesn't capture and engage these visitors to convert them into customers? The answer: <b>it's not</b>. I use various methods of inbound marketing to help you turn these strangers into brand advocates.</p>
				{% endif %}
			</div>
		</div>
		<div class="row" id="why-it-matters">
			<div class="container p-t-5 p-b-5 clearfix" id="i-can-help">
				<h1 class="text-center truly">The Methods I Use</h1>
				{% if services %}
					{% for service in services %}
						<div class="col-1-3 p-t-5 method">
							<div class="method-img" style="background: url({{ service.thumb.url }}) center; background-size: cover; border-radius: 50%;"></div>
							<h2 class="method-title red">{{ service.title }}</h2>
							<p class="method-info">{{ service.home_text|safe|removetags:"p" }}</p>
							<a class="read-more" href="{% url 'home:what' %}">Learn More</a>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
		<div class="row" id="how-i-work">
			<div class="overlay">
				<div class="container p-t-5 p-b-5 clearfix" id="how-container">
					<h1 class="text-center truly text-white">How I Work</h1>
					<div class="col-1-3 p-t-5">
						<h1 class="how p-b-5 text-center">Discovery</h1>
						<p class="text-center">The process starts with digging into your company's background and researching your niche. I work closely with you to determine who your ideal customer is and what your business' persona is. By looking through best practices, case studies, product research and and investigating your competitors, I build a baseline knowledge on your industry and am able to identify what makes you unique.</p>
					</div>
					<div class="col-1-3 p-t-5">
						<h1 class="how p-b-5 text-center">Platform</h1>
						<p class="text-center">You need a platform - a foundation from which you can market and communicate to your target audience. A great product or an exceptional service is no longer enough in the age of everything viral. From day one, my goal is to develop a platform for you to develop the platform necessary to empower your brand and grow your business.</p>
					</div>
					<div class="col-1-3 p-t-5">
						<h1 class="how p-b-5 text-center">Application</h1>
						<p class="text-center">My aim is to be an indespinsible assett to your company over the lifetime of your brand. By applying various inbound techniques consistenly over time, I help increase your conversion rates which in turn help to close more deals. I also work with you directly to implement new inbound marketing campaigns and create new profitable opportunities for your business.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="container clearfix">
				<div class="col-2-3 p-t-2 p-b-2 col-centered">
					<h2 class="workwme">Work with me</h2>
					<form action="{% url 'home:lead' %}" method="post">
						{% csrf_token %}
						{{ form }}
						<input type="submit" name="contact_submit" class="submit" value="Get In Touch"/>
					</form>
				</div>
			</div>
		</div>
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.min.js' %}"></script>
	{% endblock %}

home/templates/what.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
	{% endblock %}

	{% block title %}What I Do | Austin Bailey{% endblock %}

	{% block content %}
		<div class="row" id="what">
			<div class="overlay">
				<div class="col-3-4 col-centered">
					<h1 class="text-white text-center">I work with you to turn your <span class="red">company</span> into a local industry <span class="red">leader</span></h1>
				</div>
			</div>
		</div>
		<div class="row m-t-5 m-b-5">
			<div class="container clearfix">
				{% if services %}
					{% for service in services %}
						<div class="col-1-3">
							<a class="service-link" data-target="{{ service.id }}" href="#{{ service.title|slugify }}">
								<div class="service-img" style="background: url({{ service.image.url }}) center; background-size: cover;">
									<div class="overlay"></div>
								</div>
							</a>
							<div class="row service-desc-brief" id="{{ service.id }}">
								<h2 class="service-title p-t-5 p-b-2">{{ service.title_full }}</h2>
								<a href="#{{ service.title|slugify }}" data-target="{{ service.id }}" class="service-learn">Learn more</a>
							</div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
		<div id="stop"></div>
		{% if services %}
			{% for service in services %}
				<div class="row service-full" id="{{ service.title|slugify }}">
					<div class="col-1-3 service-img-lg" style="background: url({{ service.image.url }}); background-size: cover;"></div>
					<div class="col-2-3">
						<div class="fs-container clearfix">
							<h1 class="fs-service-title">{{ service.title_full }}</h1>
							{{ service.description|safe }}
							<a href="{% url 'home:contact' %}" class="cta-btn-inverse cta-btn-large">Get In Touch</a>
						</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.min.js' %}"></script>
	{% endblock %}

home/templates/who.html
{% extends 'base.html' %}
	{% load static from staticfiles %}

	{% block stylesheets %}
		<link rel="stylesheet" href="{% static 'home/css/style.min.css' %}" />
	{% endblock %}

	{% block title %}Who I Am | Austin Bailey{% endblock %}

	{% block content %}
		<div class="row" id="who">
			<div class="overlay">
				<div class="container clearfix" id="who-container">
					<div class="col-3-4 p-b-10 col-centered" id="who-container">
						<h1 class="text-white text-center">I'm Austin Bailey, your digital <span class="red">guru</span> and inbound marketing <span class="red">rockstar</span></h1>
						<p class="p-t-5">I'm an entrepreneurial, self-taught full stack web developer with a deep passion for learning new things. I'm 22 years old and have been learning various technologies since I was 15. I've worked with various technology companies and have experience implementing different online marketing techniques. I love to help others succeed, whether it be in business or in life. I'm an outspoken, creative individual that comes up with new, unique ideas for the people I work with daily. I'm honest, have a positive outlook on life, ambitious, and very attentive to everyone I meet.</p>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}

	{% block javascript %}
		<script src="{% static 'home/js/home.min.js' %}"></script>
	{% endblock %}